spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test
  config:
    activate:
      on-profile: ci,test,default
  sql:
    init:
      mode: always   
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

        spring:
        mvc:
        hiddenmethod:
          filter:
            enabled: true

  h2:
      console:
      enabled: true
