server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:shareit}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:user}

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:shareit
#    username: test
#    password: test
#  config:
#    activate:
#      on-profile: ci,test,default
#
