server:
  port:
    9090
  #
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  #---
  spring:
    datasource:
      driverClassName: org.postgresql.Driver 
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:shareit}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:user}
#---
#spring.config.activate.on-profile=ci,test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:shareit
#spring.datasource.username=test
#spring.datasource.password=test